/**
 * Copyright (c) 2015 by My Company
 * This file and its contents are Confidential.
 */
package com.mycompany.messages;


import com.mycompany.protocol.Company;

/**
 * Generated by John Doe from java_objects_test2.xml on 15/6/2015
 */
public class Conversations {
    /**
     * private fields 
     */
    private org.joda.time.DateTime mDate;
    private java.util.ArrayList<Conversation> mConversations;
    private Company mCompany;
    private java.util.ArrayList<org.joda.time.DateTime> mJodaDates;
    private java.util.ArrayList<java.util.Date> mNormalDates;

    /**
     * Internal Builder class for the Conversations
     */
    public static class Builder {

        private org.joda.time.DateTime mDate;
        private java.util.ArrayList<Conversation> mConversations;
        private Company mCompany;
        private java.util.ArrayList<org.joda.time.DateTime> mJodaDates;
        private java.util.ArrayList<java.util.Date> mNormalDates;

        public Builder() {
        }

        /**
         * Sets the "date" field to the value supplied 
         * 
         * @param date the value to the set into the "date" field
         * @return reference to this object instance
         */
        public Builder setDate(org.joda.time.DateTime date) {
            this.mDate = date;
            return this;
        }

        /**
         * Sets the "conversations" field to the value supplied 
         * 
         * @param conversations the value to the set into the "conversations" field
         * @return reference to this object instance
         */
        public Builder setConversations(java.util.ArrayList<Conversation> conversations) {
            this.mConversations = conversations;
            return this;
        }

        /**
         * Sets the "company" field to the value supplied 
         * 
         * @param company the value to the set into the "company" field
         * @return reference to this object instance
         */
        public Builder setCompany(Company company) {
            this.mCompany = company;
            return this;
        }

        /**
         * Sets the "joda-dates" field to the value supplied 
         * 
         * @param jodaDates the value to the set into the "joda-dates" field
         * @return reference to this object instance
         */
        public Builder setJodaDates(java.util.ArrayList<org.joda.time.DateTime> jodaDates) {
            this.mJodaDates = jodaDates;
            return this;
        }

        /**
         * Sets the "normal-dates" field to the value supplied 
         * 
         * @param normalDates the value to the set into the "normal-dates" field
         * @return reference to this object instance
         */
        public Builder setNormalDates(java.util.ArrayList<java.util.Date> normalDates) {
            this.mNormalDates = normalDates;
            return this;
        }

        /**
         * Creates the object instance 
         * @return created instance of the <code>Conversations</code>
         */
        public Conversations create() {
            return new Conversations(this);
        }
    }

    public Conversations() {
    }

    public Conversations(org.joda.time.DateTime date,
                         java.util.ArrayList<Conversation> conversations,
                         Company company,
                         java.util.ArrayList<org.joda.time.DateTime> jodaDates,
                         java.util.ArrayList<java.util.Date> normalDates) {
        mDate = date;
        mConversations = conversations;
        mCompany = company;
        mJodaDates = jodaDates;
        mNormalDates = normalDates;
    }

    /**
     * Constructor from the Builder 
     */
    protected Conversations(Builder builder) {
        mDate = builder.mDate;
        mConversations = builder.mConversations;
        mCompany = builder.mCompany;
        mJodaDates = builder.mJodaDates;
        mNormalDates = builder.mNormalDates;
    }

    /**
     * Getters 
     */

    /**
     * @return the value of the "date" field
     */
    public org.joda.time.DateTime getDate() {
        return this.mDate;
    }

    /**
     * @return the value of the "conversations" field
     */
    public java.util.ArrayList<Conversation> getConversations() {
        return this.mConversations;
    }

    /**
     * @return the value of the "company" field
     */
    public Company getCompany() {
        return this.mCompany;
    }

    /**
     * @return the value of the "joda-dates" field
     */
    public java.util.ArrayList<org.joda.time.DateTime> getJodaDates() {
        return this.mJodaDates;
    }

    /**
     * @return the value of the "normal-dates" field
     */
    public java.util.ArrayList<java.util.Date> getNormalDates() {
        return this.mNormalDates;
    }

    /**
     * Setters 
     */

    /**
     * Sets the "date" field to the value supplied 
     * 
     * @param date the value to the set into the "date" field
     * @return reference to this object instance
     */
    public Conversations setDate(org.joda.time.DateTime date) {
        this.mDate = date;
        return this;
    }

    /**
     * Sets the "conversations" field to the value supplied 
     * 
     * @param conversations the value to the set into the "conversations" field
     * @return reference to this object instance
     */
    public Conversations setConversations(java.util.ArrayList<Conversation> conversations) {
        this.mConversations = conversations;
        return this;
    }

    /**
     * Sets the "company" field to the value supplied 
     * 
     * @param company the value to the set into the "company" field
     * @return reference to this object instance
     */
    public Conversations setCompany(Company company) {
        this.mCompany = company;
        return this;
    }

    /**
     * Sets the "joda-dates" field to the value supplied 
     * 
     * @param jodaDates the value to the set into the "joda-dates" field
     * @return reference to this object instance
     */
    public Conversations setJodaDates(java.util.ArrayList<org.joda.time.DateTime> jodaDates) {
        this.mJodaDates = jodaDates;
        return this;
    }

    /**
     * Sets the "normal-dates" field to the value supplied 
     * 
     * @param normalDates the value to the set into the "normal-dates" field
     * @return reference to this object instance
     */
    public Conversations setNormalDates(java.util.ArrayList<java.util.Date> normalDates) {
        this.mNormalDates = normalDates;
        return this;
    }

}
