/**
 * Copyright (c) 2015 by My Company
 * This file and its contents are Confidential.
 */
package com.mycompany.messages;



/**
 * Generated by John Doe from java_objects_test2.xml on 15/6/2015
 */
public class EntryNotIsSet implements android.os.Parcelable {
    /**
     * private fields 
     */
    private java.util.Date mDate;
    private java.util.ArrayList<java.util.Date> mDates;
    private double mDoubleValue;
    private String mStringValue;
    private boolean mBoolValue;
    private int mIntValue;
    private long mLongValue;
    private byte mByteValue;
    private java.util.ArrayList<Long> mLongArray;
    private double mLat;
    private double mLong;

    /**
     * Internal Builder class for the EntryNotIsSet
     */
    public static class Builder {

        private java.util.Date mDate;
        private java.util.ArrayList<java.util.Date> mDates;
        private double mDoubleValue;
        private String mStringValue;
        private boolean mBoolValue;
        private int mIntValue;
        private long mLongValue;
        private byte mByteValue;
        private java.util.ArrayList<Long> mLongArray;
        private double mLat;
        private double mLong;

        public Builder() {
        }

        /**
         * Sets the "date" field to the value supplied 
         * 
         * @param date the value to the set into the "date" field
         * @return reference to this object instance
         */
        public Builder setDate(java.util.Date date) {
            this.mDate = date;
            return this;
        }

        /**
         * Sets the "dates" field to the value supplied 
         * 
         * @param dates the value to the set into the "dates" field
         * @return reference to this object instance
         */
        public Builder setDates(java.util.ArrayList<java.util.Date> dates) {
            this.mDates = dates;
            return this;
        }

        /**
         * Sets the "doubleValue" field to the value supplied 
         * 
         * @param doubleValue the value to the set into the "doubleValue" field
         * @return reference to this object instance
         */
        public Builder setDoubleValue(double doubleValue) {
            this.mDoubleValue = doubleValue;
            return this;
        }

        /**
         * Sets the "stringValue" field to the value supplied 
         * 
         * @param stringValue the value to the set into the "stringValue" field
         * @return reference to this object instance
         */
        public Builder setStringValue(String stringValue) {
            this.mStringValue = stringValue;
            return this;
        }

        /**
         * Sets the "boolValue" field to the value supplied 
         * 
         * @param boolValue the value to the set into the "boolValue" field
         * @return reference to this object instance
         */
        public Builder setBoolValue(boolean boolValue) {
            this.mBoolValue = boolValue;
            return this;
        }

        /**
         * Sets the "intValue" field to the value supplied 
         * 
         * @param intValue the value to the set into the "intValue" field
         * @return reference to this object instance
         */
        public Builder setIntValue(int intValue) {
            this.mIntValue = intValue;
            return this;
        }

        /**
         * Sets the "longValue" field to the value supplied 
         * 
         * @param longValue the value to the set into the "longValue" field
         * @return reference to this object instance
         */
        public Builder setLongValue(long longValue) {
            this.mLongValue = longValue;
            return this;
        }

        /**
         * Sets the "byteValue" field to the value supplied 
         * 
         * @param byteValue the value to the set into the "byteValue" field
         * @return reference to this object instance
         */
        public Builder setByteValue(byte byteValue) {
            this.mByteValue = byteValue;
            return this;
        }

        /**
         * Sets the "longArray" field to the value supplied 
         * 
         * @param longArray the value to the set into the "longArray" field
         * @return reference to this object instance
         */
        public Builder setLongArray(java.util.ArrayList<Long> longArray) {
            this.mLongArray = longArray;
            return this;
        }

        /**
         * Sets the "lat" field to the value supplied 
         * 
         * @param lat the value to the set into the "lat" field
         * @return reference to this object instance
         */
        public Builder setLat(double lat) {
            this.mLat = lat;
            return this;
        }

        /**
         * Sets the "long" field to the value supplied 
         * 
         * @param _long the value to the set into the "long" field
         * @return reference to this object instance
         */
        public Builder setLong(double _long) {
            this.mLong = _long;
            return this;
        }

        /**
         * Creates the object instance 
         * @return created instance of the <code>EntryNotIsSet</code>
         */
        public EntryNotIsSet create() {
            return new EntryNotIsSet(this);
        }
    }

    public EntryNotIsSet() {
    }

    public EntryNotIsSet(java.util.Date date,
                         java.util.ArrayList<java.util.Date> dates,
                         double doubleValue,
                         String stringValue,
                         boolean boolValue,
                         int intValue,
                         long longValue,
                         byte byteValue,
                         java.util.ArrayList<Long> longArray,
                         double lat,
                         double _long) {
        mDate = date;
        mDates = dates;
        mDoubleValue = doubleValue;
        mStringValue = stringValue;
        mBoolValue = boolValue;
        mIntValue = intValue;
        mLongValue = longValue;
        mByteValue = byteValue;
        mLongArray = longArray;
        mLat = lat;
        mLong = _long;
    }

    /**
     * Constructor from the Builder 
     */
    protected EntryNotIsSet(Builder builder) {
        mDate = builder.mDate;
        mDates = builder.mDates;
        mDoubleValue = builder.mDoubleValue;
        mStringValue = builder.mStringValue;
        mBoolValue = builder.mBoolValue;
        mIntValue = builder.mIntValue;
        mLongValue = builder.mLongValue;
        mByteValue = builder.mByteValue;
        mLongArray = builder.mLongArray;
        mLat = builder.mLat;
        mLong = builder.mLong;
    }

    /**
     * Implementing Parcelable interface 
     */

    /**
     * Parses the string specified using supplied formatter
     *
     * @param dateString   string to parse
     * @param format       formatter used to parse the date string
     * @return             parsed Date object or Date epoch object in case of error
     */
    private static java.util.Date parseDate(String dateString, java.text.SimpleDateFormat format) {
        java.util.Date result = new java.util.Date(0);
        try {
            result = format.parse(dateString);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return result;
    }

    @SuppressWarnings("unchecked")
    public EntryNotIsSet(android.os.Parcel in) {
        final java.text.SimpleDateFormat ISO8601_JAVA_DATE_FORMAT = new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ");
        this.mDate = parseDate(in.readString(), ISO8601_JAVA_DATE_FORMAT);
        this.mDates = new java.util.ArrayList<java.util.Date>();
        {
            java.util.ArrayList<String> tmpArray = new java.util.ArrayList<String>();
            in.readStringList(tmpArray);
            for (String date : tmpArray)
                this.mDates.add(parseDate(date, ISO8601_JAVA_DATE_FORMAT));
        };
        this.mDoubleValue = in.readDouble();
        this.mStringValue = in.readString();
        this.mBoolValue = in.readByte() != 0;
        this.mIntValue = in.readInt();
        this.mLongValue = in.readLong();
        this.mByteValue = in.readByte();
        this.mLongArray = (java.util.ArrayList<Long>)in.readSerializable();
        this.mLat = in.readDouble();
        this.mLong = in.readDouble();
    }

    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
        final java.text.SimpleDateFormat ISO8601_JAVA_DATE_FORMAT = new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ");
        out.writeString(ISO8601_JAVA_DATE_FORMAT.format(mDate));
        {
            java.util.ArrayList<String> tmpArray = new java.util.ArrayList<String>();
            for (java.util.Date date : mDates)
                tmpArray.add(ISO8601_JAVA_DATE_FORMAT.format(date));
            out.writeStringList(tmpArray);
        };
        out.writeDouble(mDoubleValue);
        out.writeString(mStringValue);
        out.writeByte((byte)(mBoolValue ? 1 : 0));
        out.writeInt(mIntValue);
        out.writeLong(mLongValue);
        out.writeByte(mByteValue);
        out.writeSerializable(mLongArray);
        out.writeDouble(mLat);
        out.writeDouble(mLong);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    public static final android.os.Parcelable.Creator<EntryNotIsSet> CREATOR = new android.os.Parcelable.Creator<EntryNotIsSet>() {
        public EntryNotIsSet createFromParcel(android.os.Parcel in) {
            return new EntryNotIsSet(in);
        }
        public EntryNotIsSet[] newArray(int size) {
            return new EntryNotIsSet[size];
        }
    };

    /**
     * Parcelable interface implementation done 
     */

    /**
     * Getters 
     */

    /**
     * @return the value of the "date" field
     */
    public java.util.Date getDate() {
        return this.mDate;
    }

    /**
     * @return the value of the "dates" field
     */
    public java.util.ArrayList<java.util.Date> getDates() {
        return this.mDates;
    }

    /**
     * @return the value of the "doubleValue" field
     */
    public double getDoubleValue() {
        return this.mDoubleValue;
    }

    /**
     * @return the value of the "stringValue" field
     */
    public String getStringValue() {
        return this.mStringValue;
    }

    /**
     * @return the value of the "boolValue" field
     */
    public boolean getBoolValue() {
        return this.mBoolValue;
    }

    /**
     * @return the value of the "intValue" field
     */
    public int getIntValue() {
        return this.mIntValue;
    }

    /**
     * @return the value of the "longValue" field
     */
    public long getLongValue() {
        return this.mLongValue;
    }

    /**
     * @return the value of the "byteValue" field
     */
    public byte getByteValue() {
        return this.mByteValue;
    }

    /**
     * @return the value of the "longArray" field
     */
    public java.util.ArrayList<Long> getLongArray() {
        return this.mLongArray;
    }

    /**
     * @return the value of the "lat" field
     */
    public double getLat() {
        return this.mLat;
    }

    /**
     * @return the value of the "long" field
     */
    public double getLong() {
        return this.mLong;
    }

    /**
     * Setters 
     */

    /**
     * Sets the "date" field to the value supplied 
     * 
     * @param date the value to the set into the "date" field
     * @return reference to this object instance
     */
    public EntryNotIsSet setDate(java.util.Date date) {
        this.mDate = date;
        return this;
    }

    /**
     * Sets the "dates" field to the value supplied 
     * 
     * @param dates the value to the set into the "dates" field
     * @return reference to this object instance
     */
    public EntryNotIsSet setDates(java.util.ArrayList<java.util.Date> dates) {
        this.mDates = dates;
        return this;
    }

    /**
     * Sets the "doubleValue" field to the value supplied 
     * 
     * @param doubleValue the value to the set into the "doubleValue" field
     * @return reference to this object instance
     */
    public EntryNotIsSet setDoubleValue(double doubleValue) {
        this.mDoubleValue = doubleValue;
        return this;
    }

    /**
     * Sets the "stringValue" field to the value supplied 
     * 
     * @param stringValue the value to the set into the "stringValue" field
     * @return reference to this object instance
     */
    public EntryNotIsSet setStringValue(String stringValue) {
        this.mStringValue = stringValue;
        return this;
    }

    /**
     * Sets the "boolValue" field to the value supplied 
     * 
     * @param boolValue the value to the set into the "boolValue" field
     * @return reference to this object instance
     */
    public EntryNotIsSet setBoolValue(boolean boolValue) {
        this.mBoolValue = boolValue;
        return this;
    }

    /**
     * Sets the "intValue" field to the value supplied 
     * 
     * @param intValue the value to the set into the "intValue" field
     * @return reference to this object instance
     */
    public EntryNotIsSet setIntValue(int intValue) {
        this.mIntValue = intValue;
        return this;
    }

    /**
     * Sets the "longValue" field to the value supplied 
     * 
     * @param longValue the value to the set into the "longValue" field
     * @return reference to this object instance
     */
    public EntryNotIsSet setLongValue(long longValue) {
        this.mLongValue = longValue;
        return this;
    }

    /**
     * Sets the "byteValue" field to the value supplied 
     * 
     * @param byteValue the value to the set into the "byteValue" field
     * @return reference to this object instance
     */
    public EntryNotIsSet setByteValue(byte byteValue) {
        this.mByteValue = byteValue;
        return this;
    }

    /**
     * Sets the "longArray" field to the value supplied 
     * 
     * @param longArray the value to the set into the "longArray" field
     * @return reference to this object instance
     */
    public EntryNotIsSet setLongArray(java.util.ArrayList<Long> longArray) {
        this.mLongArray = longArray;
        return this;
    }

    /**
     * Sets the "lat" field to the value supplied 
     * 
     * @param lat the value to the set into the "lat" field
     * @return reference to this object instance
     */
    public EntryNotIsSet setLat(double lat) {
        this.mLat = lat;
        return this;
    }

    /**
     * Sets the "long" field to the value supplied 
     * 
     * @param _long the value to the set into the "long" field
     * @return reference to this object instance
     */
    public EntryNotIsSet setLong(double _long) {
        this.mLong = _long;
        return this;
    }

}
