/**
 * Copyright (c) 2015 by My Company
 * This file and its contents are Confidential.
 */
package com.mycompany.messages;



/**
 * Generated by John Doe from java_objects_test2.xml on 15/6/2015
 */
public class Person {
    /**
     * private fields 
     */
    private final String mName;
    private final int mId;

    /**
     * Internal Builder class for the Person
     */
    public static class Builder {

        private String mName;
        private int mId;

        public Builder() {
        }

        /**
         * Sets the "name" field to the value supplied 
         * 
         * @param name the value to the set into the "name" field
         * @return reference to this object instance
         */
        public Builder setName(String name) {
            this.mName = name;
            return this;
        }

        /**
         * Sets the "id" field to the value supplied 
         * 
         * @param id the value to the set into the "id" field
         * @return reference to this object instance
         */
        public Builder setId(int id) {
            this.mId = id;
            return this;
        }

        /**
         * Creates the object instance 
         * @return created instance of the <code>Person</code>
         */
        public Person create() {
            return new Person(this);
        }
    }

    /**
     * Constructor from the Builder 
     */
    protected Person(Builder builder) {
        mName = builder.mName;
        mId = builder.mId;
    }

    /**
     * Getters 
     */

    /**
     * @return the value of the "name" field
     */
    public String getName() {
        return this.mName;
    }

    /**
     * @return the value of the "id" field
     */
    public int getId() {
        return this.mId;
    }

}
