/**
 * Copyright (c) 2015 by My Company
 * This file and its contents are Confidential.
 */
package com.structs.test;



/**
 * Generated by John Doe from java_objects_test1.xml on 15/6/2015
 */
public class WorkPackage {
    /**
     * private fields 
     */
    private long mCustomerId;
    private long mWorkcodeId;
    private long mProjectId;

    /**
     * Internal Builder class for the WorkPackage
     */
    public static class Builder {

        private long mCustomerId;
        private long mWorkcodeId;
        private long mProjectId;

        public Builder() {
        }

        /**
         * Sets the "customer-id" field to the value supplied 
         * 
         * @param customerId the value to the set into the "customer-id" field
         * @return reference to this object instance
         */
        public Builder setCustomerId(long customerId) {
            this.mCustomerId = customerId;
            return this;
        }

        /**
         * Sets the "workcode-id" field to the value supplied 
         * 
         * @param workcodeId the value to the set into the "workcode-id" field
         * @return reference to this object instance
         */
        public Builder setWorkcodeId(long workcodeId) {
            this.mWorkcodeId = workcodeId;
            return this;
        }

        /**
         * Sets the "project-id" field to the value supplied 
         * 
         * @param projectId the value to the set into the "project-id" field
         * @return reference to this object instance
         */
        public Builder setProjectId(long projectId) {
            this.mProjectId = projectId;
            return this;
        }

        /**
         * Creates the object instance 
         * @return created instance of the <code>WorkPackage</code>
         */
        public WorkPackage create() {
            return new WorkPackage(this);
        }
    }

    public WorkPackage() {
    }

    public WorkPackage(long customerId,
                       long workcodeId,
                       long projectId) {
        mCustomerId = customerId;
        mWorkcodeId = workcodeId;
        mProjectId = projectId;
    }

    /**
     * Constructor from the Builder 
     */
    protected WorkPackage(Builder builder) {
        mCustomerId = builder.mCustomerId;
        mWorkcodeId = builder.mWorkcodeId;
        mProjectId = builder.mProjectId;
    }

    /**
     * Getters 
     */

    /**
     * @return the value of the "customer-id" field
     */
    public long getCustomerId() {
        return this.mCustomerId;
    }

    /**
     * @return the value of the "workcode-id" field
     */
    public long getWorkcodeId() {
        return this.mWorkcodeId;
    }

    /**
     * @return the value of the "project-id" field
     */
    public long getProjectId() {
        return this.mProjectId;
    }

    /**
     * Setters 
     */

    /**
     * Sets the "customer-id" field to the value supplied 
     * 
     * @param customerId the value to the set into the "customer-id" field
     * @return reference to this object instance
     */
    public WorkPackage setCustomerId(long customerId) {
        this.mCustomerId = customerId;
        return this;
    }

    /**
     * Sets the "workcode-id" field to the value supplied 
     * 
     * @param workcodeId the value to the set into the "workcode-id" field
     * @return reference to this object instance
     */
    public WorkPackage setWorkcodeId(long workcodeId) {
        this.mWorkcodeId = workcodeId;
        return this;
    }

    /**
     * Sets the "project-id" field to the value supplied 
     * 
     * @param projectId the value to the set into the "project-id" field
     * @return reference to this object instance
     */
    public WorkPackage setProjectId(long projectId) {
        this.mProjectId = projectId;
        return this;
    }


    public void dummy() {
    }        
      
    public void anotherDummy() {
    }        
      
}
