/**
 * Copyright (c) 2014 by My Company
 * This file and its contents are Confidential.
 */
package com.mycompany.users;



/**
 * Generated by The Author from java_objects_test1.xml on 15/6/2015
 */
public class Employee implements android.os.Parcelable {
    /**
     * private fields 
     */
    private final int mId;
    private final PersonalUserData mData;
    private final boolean mProbation;
    private final java.util.Date mStarted;

    /**
     * Internal Builder class for the Employee
     */
    public static class Builder {

        private int mId;
        private PersonalUserData mData;
        private boolean mProbation;
        private java.util.Date mStarted;

        public Builder() {
        }

        /**
         * Sets the "id" field to the value supplied 
         * 
         * @param id the value to the set into the "id" field
         * @return reference to this object instance
         */
        public Builder setId(int id) {
            this.mId = id;
            return this;
        }

        /**
         * Sets the "data" field to the value supplied 
         * 
         * @param data the value to the set into the "data" field
         * @return reference to this object instance
         */
        public Builder setData(PersonalUserData data) {
            this.mData = data;
            return this;
        }

        /**
         * Sets the "probation" field to the value supplied 
         * 
         * @param probation the value to the set into the "probation" field
         * @return reference to this object instance
         */
        public Builder setProbation(boolean probation) {
            this.mProbation = probation;
            return this;
        }

        /**
         * Sets the "started" field to the value supplied 
         * 
         * @param started the value to the set into the "started" field
         * @return reference to this object instance
         */
        public Builder setStarted(java.util.Date started) {
            this.mStarted = started;
            return this;
        }

        /**
         * Creates the object instance 
         * @return created instance of the <code>Employee</code>
         */
        public Employee create() {
            return new Employee(this);
        }
    }

    /**
     * Constructor from the Builder 
     */
    protected Employee(Builder builder) {
        mId = builder.mId;
        mData = builder.mData;
        mProbation = builder.mProbation;
        mStarted = builder.mStarted;
    }

    /**
     * Implementing Parcelable interface 
     */

    /**
     * Parses the string specified using supplied formatter
     *
     * @param dateString   string to parse
     * @param format       formatter used to parse the date string
     * @return             parsed Date object or Date epoch object in case of error
     */
    private static java.util.Date parseDate(String dateString, java.text.SimpleDateFormat format) {
        java.util.Date result = new java.util.Date(0);
        try {
            result = format.parse(dateString);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return result;
    }

    @SuppressWarnings("unchecked")
    public Employee(android.os.Parcel in) {
        final java.text.SimpleDateFormat ISO8601_JAVA_DATE_FORMAT = new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ");
        this.mId = in.readInt();
        this.mData = (com.mycompany.users.PersonalUserData)in.readParcelable(com.mycompany.users.PersonalUserData.class.getClassLoader());
        this.mProbation = in.readByte() != 0;
        this.mStarted = parseDate(in.readString(), ISO8601_JAVA_DATE_FORMAT);
    }

    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
        final java.text.SimpleDateFormat ISO8601_JAVA_DATE_FORMAT = new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ");
        out.writeInt(mId);
        out.writeParcelable(mData, flags);
        out.writeByte((byte)(mProbation ? 1 : 0));
        out.writeString(ISO8601_JAVA_DATE_FORMAT.format(mStarted));
    }

    @Override
    public int describeContents() {
        return 0;
    }

    public static final android.os.Parcelable.Creator<Employee> CREATOR = new android.os.Parcelable.Creator<Employee>() {
        public Employee createFromParcel(android.os.Parcel in) {
            return new Employee(in);
        }
        public Employee[] newArray(int size) {
            return new Employee[size];
        }
    };

    /**
     * Parcelable interface implementation done 
     */

    /**
     * Getters 
     */

    /**
     * @return the value of the "id" field
     */
    public int getId() {
        return this.mId;
    }

    /**
     * @return the value of the "data" field
     */
    public PersonalUserData getData() {
        return this.mData;
    }

    /**
     * @return the value of the "probation" field
     */
    public boolean getProbation() {
        return this.mProbation;
    }

    /**
     * @return the value of the "started" field
     */
    public java.util.Date getStarted() {
        return this.mStarted;
    }


    public void dumpEmployee() {
        System.out.println("Employee " + mData.getName() + " started at " + org.joda.time.format.DateTimeFormat.shortDate().print(mStarted));        
    }        
      
}
