/**
 * Copyright (c) 2015 by My Company
 * This file and its contents are Confidential.
 */
package com.arrays.test;



/**
 * Generated by John Doe from java_objects_test1.xml on 15/6/2015
 */
public class EmptyObject {
    /**
     * private fields 
     */

    public EmptyObject() {
    }

    public EmptyObject() {
    }

    /**
     * Getters 
     */

    /**
     * Setters 
     */

}
