/**
 * Copyright (c) 2015 by My Company
 * This file and its contents are Confidential.
 */
package com.arrays.test;



/**
 * Generated by John Doe from java_objects_test1.xml on 15/6/2015
 */
public class FieldsTest {
    /**
     * private fields 
     */
    private CommandLineVersion1 m0field00;
    private CommandLineVersion2 m1field01;
    private CommandLine mField1;
    private CommandLine mField2;
    private com.structs.WorkPackage mField3;
    private java.util.ArrayList<CommandLine> mArray1;
    private java.util.ArrayList<CommandLine> mArray2;
    private java.util.ArrayList<com.structs.test.WorkPackage> mArray3;

    public FieldsTest() {
    }

    public FieldsTest(CommandLineVersion1 _0field00,
                      CommandLineVersion2 _1field01,
                      CommandLine field1,
                      CommandLine field2,
                      com.structs.WorkPackage field3,
                      java.util.ArrayList<CommandLine> array1,
                      java.util.ArrayList<CommandLine> array2,
                      java.util.ArrayList<com.structs.test.WorkPackage> array3) {
        m0field00 = _0field00;
        m1field01 = _1field01;
        mField1 = field1;
        mField2 = field2;
        mField3 = field3;
        mArray1 = array1;
        mArray2 = array2;
        mArray3 = array3;
    }

    /**
     * Getters 
     */

    /**
     * @return the value of the "0field00" field
     */
    public CommandLineVersion1 get0field00() {
        return this.m0field00;
    }

    /**
     * @return the value of the "1field01" field
     */
    public CommandLineVersion2 get1field01() {
        return this.m1field01;
    }

    /**
     * @return the value of the "field1" field
     */
    public CommandLine getField1() {
        return this.mField1;
    }

    /**
     * @return the value of the "field2" field
     */
    public CommandLine getField2() {
        return this.mField2;
    }

    /**
     * @return the value of the "field3" field
     */
    public com.structs.WorkPackage getField3() {
        return this.mField3;
    }

    /**
     * @return the value of the "array1" field
     */
    public java.util.ArrayList<CommandLine> getArray1() {
        return this.mArray1;
    }

    /**
     * @return the value of the "array2" field
     */
    public java.util.ArrayList<CommandLine> getArray2() {
        return this.mArray2;
    }

    /**
     * @return the value of the "array3" field
     */
    public java.util.ArrayList<com.structs.test.WorkPackage> getArray3() {
        return this.mArray3;
    }

    /**
     * Setters 
     */

    /**
     * Sets the "0field00" field to the value supplied 
     * 
     * @param _0field00 the value to the set into the "0field00" field
     * @return reference to this object instance
     */
    public FieldsTest set0field00(CommandLineVersion1 _0field00) {
        this.m0field00 = _0field00;
        return this;
    }

    /**
     * Sets the "1field01" field to the value supplied 
     * 
     * @param _1field01 the value to the set into the "1field01" field
     * @return reference to this object instance
     */
    public FieldsTest set1field01(CommandLineVersion2 _1field01) {
        this.m1field01 = _1field01;
        return this;
    }

    /**
     * Sets the "field1" field to the value supplied 
     * 
     * @param field1 the value to the set into the "field1" field
     * @return reference to this object instance
     */
    public FieldsTest setField1(CommandLine field1) {
        this.mField1 = field1;
        return this;
    }

    /**
     * Sets the "field2" field to the value supplied 
     * 
     * @param field2 the value to the set into the "field2" field
     * @return reference to this object instance
     */
    public FieldsTest setField2(CommandLine field2) {
        this.mField2 = field2;
        return this;
    }

    /**
     * Sets the "field3" field to the value supplied 
     * 
     * @param field3 the value to the set into the "field3" field
     * @return reference to this object instance
     */
    public FieldsTest setField3(com.structs.WorkPackage field3) {
        this.mField3 = field3;
        return this;
    }

    /**
     * Sets the "array1" field to the value supplied 
     * 
     * @param array1 the value to the set into the "array1" field
     * @return reference to this object instance
     */
    public FieldsTest setArray1(java.util.ArrayList<CommandLine> array1) {
        this.mArray1 = array1;
        return this;
    }

    /**
     * Sets the "array2" field to the value supplied 
     * 
     * @param array2 the value to the set into the "array2" field
     * @return reference to this object instance
     */
    public FieldsTest setArray2(java.util.ArrayList<CommandLine> array2) {
        this.mArray2 = array2;
        return this;
    }

    /**
     * Sets the "array3" field to the value supplied 
     * 
     * @param array3 the value to the set into the "array3" field
     * @return reference to this object instance
     */
    public FieldsTest setArray3(java.util.ArrayList<com.structs.test.WorkPackage> array3) {
        this.mArray3 = array3;
        return this;
    }

}
