/**
 * Copyright (c) 2015 by My Company
 * This file and its contents are Confidential.
 */
package com.mycompany.example;



/**
 * Generated by John Doe from java_objects_test2.xml on 15/6/2015
 */
public class Conversation {
    /**
     * private fields 
     */

    public Conversation() {
    }

    public Conversation() {
    }

    /**
     * Getters 
     */

    /**
     * Setters 
     */

}
