/**
 * Copyright (c) 2015 by My Company
 * This file and its contents are Confidential.
 */
package com.mycompany.example;



/**
 * Generated by John Doe from java_objects_test2.xml on 15/6/2015
 */
public class UserData implements android.os.Parcelable {
    /**
     * private fields 
     */
    private String mName;
    private String mOccupation;
    private int mAge;
    private java.util.ArrayList<java.util.Date> mVisits;

    public UserData() {
    }

    public UserData(String name,
                    String occupation,
                    int age,
                    java.util.ArrayList<java.util.Date> visits) {
        mName = name;
        mOccupation = occupation;
        mAge = age;
        mVisits = visits;
    }

    /**
     * Implementing Parcelable interface 
     */

    /**
     * Parses the string specified using supplied formatter
     *
     * @param dateString   string to parse
     * @param format       formatter used to parse the date string
     * @return             parsed Date object or Date epoch object in case of error
     */
    private static java.util.Date parseDate(String dateString, java.text.SimpleDateFormat format) {
        java.util.Date result = new java.util.Date(0);
        try {
            result = format.parse(dateString);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return result;
    }

    @SuppressWarnings("unchecked")
    public UserData(android.os.Parcel in) {
        final java.text.SimpleDateFormat ISO8601_JAVA_DATE_FORMAT = new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ");
        this.mName = in.readString();
        this.mOccupation = in.readString();
        this.mAge = in.readInt();
        this.mVisits = new java.util.ArrayList<java.util.Date>();
        {
            java.util.ArrayList<String> tmpArray = new java.util.ArrayList<String>();
            in.readStringList(tmpArray);
            for (String date : tmpArray)
                this.mVisits.add(parseDate(date, ISO8601_JAVA_DATE_FORMAT));
        };
    }

    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
        final java.text.SimpleDateFormat ISO8601_JAVA_DATE_FORMAT = new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ");
        out.writeString(mName);
        out.writeString(mOccupation);
        out.writeInt(mAge);
        {
            java.util.ArrayList<String> tmpArray = new java.util.ArrayList<String>();
            for (java.util.Date date : mVisits)
                tmpArray.add(ISO8601_JAVA_DATE_FORMAT.format(date));
            out.writeStringList(tmpArray);
        };
    }

    @Override
    public int describeContents() {
        return 0;
    }

    public static final android.os.Parcelable.Creator<UserData> CREATOR = new android.os.Parcelable.Creator<UserData>() {
        public UserData createFromParcel(android.os.Parcel in) {
            return new UserData(in);
        }
        public UserData[] newArray(int size) {
            return new UserData[size];
        }
    };

    /**
     * Parcelable interface implementation done 
     */

    /**
     * Getters 
     */

    /**
     * @return the value of the "name" field
     */
    public String getName() {
        return this.mName;
    }

    /**
     * @return the value of the "occupation" field
     */
    public String getOccupation() {
        return this.mOccupation;
    }

    /**
     * @return the value of the "age" field
     */
    public int getAge() {
        return this.mAge;
    }

    /**
     * @return the value of the "visits" field
     */
    public java.util.ArrayList<java.util.Date> getVisits() {
        return this.mVisits;
    }

    /**
     * Setters 
     */

    /**
     * Sets the "name" field to the value supplied 
     * 
     * @param name the value to the set into the "name" field
     * @return reference to this object instance
     */
    public UserData setName(String name) {
        this.mName = name;
        return this;
    }

    /**
     * Sets the "occupation" field to the value supplied 
     * 
     * @param occupation the value to the set into the "occupation" field
     * @return reference to this object instance
     */
    public UserData setOccupation(String occupation) {
        this.mOccupation = occupation;
        return this;
    }

    /**
     * Sets the "age" field to the value supplied 
     * 
     * @param age the value to the set into the "age" field
     * @return reference to this object instance
     */
    public UserData setAge(int age) {
        this.mAge = age;
        return this;
    }

    /**
     * Sets the "visits" field to the value supplied 
     * 
     * @param visits the value to the set into the "visits" field
     * @return reference to this object instance
     */
    public UserData setVisits(java.util.ArrayList<java.util.Date> visits) {
        this.mVisits = visits;
        return this;
    }

}
