/**
 * Copyright (c) 2015 by My Company
 * This file and its contents are Confidential.
 */
package com.mycompany.protocol;


import com.mycompany.example.Employee;

/**
 * Generated by John Doe from java_objects_test2.xml on 15/6/2015
 */
public class Company implements android.os.Parcelable {
    /**
     * private fields 
     */
    private String mName;
    private java.util.ArrayList<Employee> mEmployees;
    private java.util.ArrayList<Integer> mIds;

    public Company() {
    }

    public Company(String name,
                   java.util.ArrayList<Employee> employees,
                   java.util.ArrayList<Integer> ids) {
        mName = name;
        mEmployees = employees;
        mIds = ids;
    }

    /**
     * Implementing Parcelable interface 
     */

    @SuppressWarnings("unchecked")
    public Company(android.os.Parcel in) {
        this.mName = in.readString();
        this.mEmployees = new java.util.ArrayList<Employee>();  in.readTypedList(mEmployees, com.mycompany.example.Employee.CREATOR);
        this.mIds = (java.util.ArrayList<Integer>)in.readSerializable();
    }

    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
        out.writeString(mName);
        out.writeTypedList(mEmployees);
        out.writeSerializable(mIds);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    public static final android.os.Parcelable.Creator<Company> CREATOR = new android.os.Parcelable.Creator<Company>() {
        public Company createFromParcel(android.os.Parcel in) {
            return new Company(in);
        }
        public Company[] newArray(int size) {
            return new Company[size];
        }
    };

    /**
     * Parcelable interface implementation done 
     */

    /**
     * Getters 
     */

    /**
     * @return the value of the "name" field
     */
    public String getName() {
        return this.mName;
    }

    /**
     * @return the value of the "employees" field
     */
    public java.util.ArrayList<Employee> getEmployees() {
        return this.mEmployees;
    }

    /**
     * @return the value of the "ids" field
     */
    public java.util.ArrayList<Integer> getIds() {
        return this.mIds;
    }

    /**
     * Setters 
     */

    /**
     * Sets the "name" field to the value supplied 
     * 
     * @param name the value to the set into the "name" field
     * @return reference to this object instance
     */
    public Company setName(String name) {
        this.mName = name;
        return this;
    }

    /**
     * Sets the "employees" field to the value supplied 
     * 
     * @param employees the value to the set into the "employees" field
     * @return reference to this object instance
     */
    public Company setEmployees(java.util.ArrayList<Employee> employees) {
        this.mEmployees = employees;
        return this;
    }

    /**
     * Sets the "ids" field to the value supplied 
     * 
     * @param ids the value to the set into the "ids" field
     * @return reference to this object instance
     */
    public Company setIds(java.util.ArrayList<Integer> ids) {
        this.mIds = ids;
        return this;
    }

}
